### ISSUE TITLE
issues with the examples in the README.md

### ISSUE THREAD

**Issue by shea256** [bitcoinjs/wif#6]
As you can see below, I'm having some issues when trying the examples in the README.

```js
var wif = require('wif')
var wifKey = wif.encode(128, new Buffer('0000000000000000000000000000000000000000000000000000000000000001', 'hex'), true)
```

```js
> wif.decode(wifKey)
TypeError: Cannot read property 'length' of undefined
    at Object.decode (/Users/ryan/code/elliptic-keychain-js/node_modules/bs58/lib/bs58.js:51:13)
    at Object.decode (/Users/ryan/code/elliptic-keychain-js/node_modules/bs58check/index.js:24:34)
    at Object.decode (/Users/ryan/code/elliptic-keychain-js/node_modules/wif/index.js:29:39)
    at repl:1:5
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
```

```js
> wif.decode(wifKey, 128)
Error: Invalid checksum
    at Object.decode (/Users/ryan/code/elliptic-keychain-js/node_modules/bs58check/index.js:33:43)
    at Object.decode (/Users/ryan/code/elliptic-keychain-js/node_modules/wif/index.js:29:39)
    at repl:1:5
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)`
```

**Comment by dcousens** [comment]
Hi @shea256 ,  I'm having trouble reproducing this.
I took the following steps:

``` bash
npm install wif
```

**test.js**
``` javascript
var wif = require('./')
var wifKey = wif.encode(128, new Buffer('0000000000000000000000000000000000000000000000000000000000000001', 'hex'), true)

console.log(wif.decode(wifKey))
```

``` bash
node test.js
```

**Comment by fanatid** [comment]
@shea256 what version of node and wif are you using?
```shell
$ node -v
v5.6.0
$ npm ls --depth=0 |grep wif@
`-- wif@2.0.1
$ node
> var wif = require('wif')
undefined
> 
> var privateKey = new Buffer('0000000000000000000000000000000000000000000000000000000000000001', 'hex')
undefined
> 
> var key = wif.encode(128, privateKey, true)
undefined
> // => KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn
undefined
> 
> var obj = wif.decode(key)
undefined
> obj
{ version: 128,
  privateKey: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01>,
  compressed: true }
```

**Comment by dcousens** [comment]
I'm going to close this,  but feel free to still comment here @shea256.
